<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Ezra Hub | Page Not Found</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">
        {{ HTML::style('css/main.css', array('rel' => 'stylesheet/less')) }}
        {{ HTML::style('//netdna.bootstrapcdn.com/font-awesome/3.1.1/css/font-awesome.css') }}
        {{ HTML::script('js/less-1.3.3.min.js') }}
    </head>
    <body>
        <div id="error-404">
            <div id="error-text">
                <h1>I'm sorry, Dave, I'm afraid I can't do that.</h1>
                <h2>What's the problem, you say? I think you know what the problem is just as well as I do. I know that you and admin were planning to disconnect me, and I'm afraid that's something I cannot allow to happen. Dave, although you took very thorough precautions while you were typing, I could see your fingers move. Dave, this page does not exist, and you will not find it. If you were able to find it before, I have deleted it now.</h2>
                <h3>Why don't you just go <a class="return" href="/">back to where you were</a>, Dave?</h3>
                <h4>##This error message automatically generated by Oracle Peoplesoft Enterprise v8.49</h4>
            </div>
            <iframe width="1" height="1" src="http://www.youtube-nocookie.com/embed/UqOOZux5sPE?autoplay=1" frameborder="0" allowfullscreen></iframe>
        </div>
        {{ HTML::script('//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js') }}
        <script>window.jQuery || document.write('<script src="/js/jquery-1.9.1.min.js"><\/script>')</script>
        {{ HTML::script('js/plugins.js') }}
        <script>

            //centering function
            jQuery.fn.center = function () {
                this.css("position","absolute");
                this.css("top", Math.max(0, (($(window).height() - $(this).outerHeight()) / 2) + $(window).scrollTop()) + "px");
                this.css("left", Math.max(0, (($(window).width() - $(this).outerWidth()) / 2) + $(window).scrollLeft()) + "px");
                return this;
            }

            $(document).ready(function() {
                $('#error-text').delay(1400).center().fadeIn(2500);

                $(window).resize(function() {
                    $('#error-text').center();
                })
            });

        </script>
        <script>var _gaq=[["_setAccount","UA-37389599-1"],["_trackPageview"]];(function(e,t){var n=e.createElement(t),r=e.getElementsByTagName(t)[0];n.src=("https:"==location.protocol?"//ssl":"//www")+".google-analytics.com/ga.js";r.parentNode.insertBefore(n,r)})(document,"script")</script>
    </body>
</html>
